language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  - CI=true
  script:
    - npm run build-storybook  #不加默认运行npmtest
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  loacal_dir:storybook-static
  on:
    branch: test2